### ISSUE TITLE
Can I migrate spring-security-oauth2 project to spring security 5.1.X

### ISSUE THREAD

**Issue by hezhangjian** [jgrandja/spring-security-oauth-5-2-migrate#1]
For the reason of company's open source policy. In this december, I can't use spring security 5.2.X. If use spring security 5.1.X, can I migrate?

**Comment by jgrandja** [comment]
@Shoothzj 

> If use spring security 5.1.X, can I migrate?

It depends what features you are using in Spring Security OAuth 2.x.

Take a look at the reference doc to see what features are provided in [5.1.x](https://docs.spring.io/spring-security/site/docs/5.1.7.RELEASE/reference/htmlsingle/#oauth2client) and [5.2.x](https://docs.spring.io/spring-security/site/docs/5.2.1.RELEASE/reference/htmlsingle/#oauth2) and you should be able to figure it out.
