### ISSUE TITLE
Why is there a UserDetailsService for password flow?

### ISSUE THREAD

**Issue by spc16670** [jgrandja/spring-security-oauth-5-2-migrate#2]
The example seems to be suggesting that UserDetailsService is required for oauth password flow. 
There appears to be no requirement to explicitly configure the service for authorization code flow. 

I was hoping to get some advice from [StackOverflow](https://stackoverflow.com/questions/59383562/spring-security-5-2-password-flow), with no luck so far...

**Comment by jgrandja** [comment]
@spc16670 The `UserDetailsService` is required to authenticate the user attempting to login via [http.formLogin()](https://github.com/jgrandja/spring-security-oauth-5-2-migrate/blob/master/client-app/src/main/java/org/springframework/security/oauth/samples/config/SecurityConfig.java#L51).

It is NOT used for any of the authorization grant flows including the `password` grant. For the `password` grant, the username/password credentials that are passed in the request are used to authenticate the user's credentials at the provider, which in this sample is keycloak. Therefore, the user is registered with the provider - keycloak.
