### ISSUE TITLE
Authenticate users via Resource Owner Password Credentials

### ISSUE THREAD

**Issue by rigon** [jgrandja/spring-security-oauth-5-2-migrate#3]
Is it possible to configure Spring Boot to authenticate users using the OAuth2 Resource Owner Password Grant?
This question was raised also in [StackOverflow](https://stackoverflow.com/a/59442575)

The password grant implemented in this repository is very similar, but only works with a HTTP Client to make requests to another service. The client is setup trough an endpoint ("/authorize", params = "grant_type=password") and it is preserved in the session.

Is it possible to do something similar, but to provide authentication for its own applicaton?

**Comment by jgrandja** [comment]
@rigon The first thing I'd like to clarify is that OAuth 2.0 only deals with **Authorization**. **It does not address Authentication**. That's where [OpenID Connect](https://openid.net/specs/openid-connect-core-1_0.html) comes in, which addresses Authentication and is built on top of OAuth 2.0 as an extension.

Therefore, authenticating a user to an application using the `password` grant is an invalid use case and is not recommended. The `password` grant type (and the other 3 standard grant types) are used by the Client to obtain an access token, which usually requires user authorization in the form of an authorization grant. For the `password` grant type, the authorization grant is the user's credentials that are passed in the token request. After the Client receives the token it uses it to access protected resources. It cannot authenticate a user to the application in this flow. Use OpenID Connect if you require authentication.

Here is a link to the [`password`](https://tools.ietf.org/html/rfc6749#section-1.3.3) grant type for further information.

**Comment by rigon** [comment]
Let me clarify: the password grant should only be used for authorization and the authentication must be done by other means like e.g. login form?

This leads me to the next question. It looks to me that the password grant is very useful in the context of a proxy. In this project, the [WebClient](https://github.com/jgrandja/spring-security-oauth-5-2-migrate/blob/master/client-app/src/main/java/org/springframework/security/oauth/samples/config/WebClientConfig.java#L50) is configured with OAuth2 client to add the Authorization header in the requests to the resource server. If we have many endpoints that we want just forward them, it is easier to implement with a proxy solution. Spring offers that, the Spring Cloud Gateway.

I was trying to follow this approach, but Spring Cloud Gateway is reactive. Because of that the code is significantly different than the code used [here](https://github.com/jgrandja/spring-security-oauth-5-2-migrate/blob/master/client-app/src/main/java/org/springframework/security/oauth/samples/config/WebClientConfig.java). Am I in right path?

**Comment by jgrandja** [comment]
@rigon I would highly encourage you to read the [OAuth 2.0 Authorization Framework](https://tools.ietf.org/html/rfc6749). The better you will understand the concepts and various protocol flows for the specific grant types.

Also, the [OAuth 2.0 Client](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#oauth2client) documentation is also highly recommended in order to gain a solid understanding how Spring Security implements OAuth 2.0 client-role.
