### ISSUE TITLE
Demonstrate XML config

### ISSUE THREAD

**Issue by derylspielman** [jgrandja/spring-security-oauth-5-2-migrate#4]
All Spring docs either use Spring Boot starters or non-Spring Boot with Java Config extending `WebSecurityConfigurerAdapter`. We have a pure XML config of Spring security so cannot extend `WebSecurityConfigurerAdapter` as it duplicates beans. How do you configure your examples with pure XML config or potentially with a mix of both Java config and XML config?

**Comment by jgrandja** [comment]
@derylspielman XML support was just introduced in the 5.3 release. Please see the oauth2Login [sample](https://github.com/spring-projects/spring-security/tree/master/samples/xml/oauth2login).
