### ISSUE TITLE
What is going on?

### ISSUE THREAD

**Issue by stephenmontgomery** [jgrandja/spring-security-oauth-5-2-migrate#5]
I've wasted a few hours on this and given up.

1. Do u not need to configure messaging-client somewhere? It's certainly not in the keycloak realm json.
2. Keycloak server is 7. New version is 9.
3. Why am I logging on as user1? Is this user supposed to be defined in keycloak (spoiler it's not) as opposed to an in-memory one.
4. Given the breaking changes (hence this migration guide) and the subtle differences between SS and SS OAuth, this hasn't helped at all - it just muddies the water even further.

**Comment by jgrandja** [comment]
@stephenmontgomery This was a major miss on my end. Sincere apologies. Somehow I missed updating the Keycloak script and realm configuration from my local Keycloak install to this sample. Obviously, I was off that day :(

I just pushed the updates so please try again. I've tested this on my end and it should work now.
Let me know if you run into any other issues.
Sorry once again.

**Comment by stephenmontgomery** [comment]
Good man, thanks for the quick turnaround - I'll take a look now. 
Sorry for being short too - u got me at the end of a (very long) day spent googling/sifting thro lots of OAuth articles/tutorials etc...

**Comment by jgrandja** [comment]
No worries. It could be frustrating when things don't work as they say they should.
