### ISSUE TITLE
Good references to replace AuthorizationServerConfigurerAdapter in Spring Security

### ISSUE THREAD

**Issue by yfaney** [jgrandja/spring-security-oauth-5-2-migrate#7]
Hi, our team is clearing our tech debt in Spring Security and realized that Spring Security OAuth2 component is being deprecated and replaced as a part of Spring Security 5.2 or higher.

I am currently working on replacing the deprecated APIs with the newly introduced ones in Spring Security 5.3.3 and am stuck on replacing AuthorizationServerConfigurerAdapter. Tried finding a good example or the equivalent behaviors in WebSecurityConfigurerAdapter but couldn't quite get a good luck.

I was wondering if there is any good references to replace the deprecated APIs with the new ones or not. What I am interested in are the following interfaces:

TokenStore
TokenEnhancer
TokenConverter

I would be grateful if you could give me any good advices or directions.

Thanks.

Regards,
Younghwan Jang

**Comment by jgrandja** [comment]
@yfaney Did you see this [announcement](https://spring.io/blog/2020/04/15/announcing-the-spring-authorization-server)?

The [Spring Authorization Server](https://github.com/spring-projects-experimental/spring-authorization-server) will deliver OAuth 2.0 Authorization Server capability, which will replace the legacy `AuthorizationServerConfigurerAdapter`. This is a complete re-write so the interfaces/classes will be very different. We are in early stages of development so keep posted with the development.

**Comment by yfaney** [comment]
@jgrandja Yes I saw the announcement. I was wondering if I can find the right 1 on 1 replacement for TokenConverter things even if Authorization Server is not supported there.
Thanks for your reply and I will look forward to hearing the updates about the new Spring Authorization Server.
Have a great day!
